<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_addres</name>
   <tag></tag>
   <elementGuidId>10718766-237d-4ef5-9f35-ef73a0414304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td/textarea</value>
   </webElementProperties>
</WebElementEntity>
