<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_paymentcode</name>
   <tag></tag>
   <elementGuidId>917177ef-17ad-42d2-9b18-69023928c97b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/span[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/span[4]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Frame/iFrame</value>
   </webElementProperties>
</WebElementEntity>
